learning_site/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_details,
        name='text'),

    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail,
        name='quiz'),
    url(r'(?P<course_pk>\d+)/qy(?P<step_pk>\d+)/$', views.query_detail,
        name='query'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create,
        name='create_quiz'),

    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/create_query/$', views.query_create,
        name='create_query'),
  #  url(r'(?p<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$', views.create_question,
  #      name='create_question'),

    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>tf|mc)/$', views.create_question,
        name='create_question'),



    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form,
        name='create_answer'),


    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),

    url(r'(?P<pk>\d+)v/$', views.feeder_value, name='value'),


]

learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.hello_world, name='home'),
    url(r'^$', views.test, name='test'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

learning_site/courses/forms.py
from django import forms

from . import models

#create quiz form


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',

            'total_answers',



        ]

class FormQuiz(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [

            'answer_1',
            'answer_2',


        ]


class QueryForm(forms.ModelForm):
    class Meta:
        model = models.Query
        fields = [

            'rating',
            'feedback',



        ]

class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [

            'order',
            'prompt',





        ]




class BackTime(forms.ModelForm):
    class Meta:
        model = models.BackTime
        fields = [

            'backtimes',

        ]



class AnswersForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct',


        ]

class SelectedForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'selected',

        ]

learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course, Step, Text, Query, Quiz
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
import logging
from django.http import HttpResponse

from . import forms
from . import models

# Include the `fusioncharts.py` file that contains functions to embed the charts.
from .static import fusioncharts





def course_list(request):
    courses = models.Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def test(request):
    return HttpResponse("You're looking at question %s.")



def course_detail(request, pk):
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                   key=lambda step: step.order)
    return render(request, 'courses/course_detail.html', {
            'course': course,
            'steps': steps})



def quiz_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)

    print(step.id)   #Quiz id

    #now get the question id

    question_id = models.Question.objects.filter(quiz_id=step.id).values("id")
    print(question_id) # question_id

    steps = models.Answer.objects.filter(question_id=question_id, text_version='1')
    steps_version2 = models.Answer.objects.filter(question_id=question_id, text_version='2')
    steps_wrong = models.Answer.objects.filter(question_id=question_id,correct='0')



    order = models.Answer.objects.filter(question_id=question_id).values("order")
    print(order)  # orders

    correct = models.Answer.objects.filter(question_id=question_id).values("correct")
    print(correct)  # orders

    #    step_order = get_object_or_404(models.Answer, question_id = question_id)


    #now get the question id
    form = forms.SelectedForm()  #create blank form



 #   print("steps_version2",steps_versions)
    answer_correct_order = models.Answer.objects.filter(correct="1", question_id=question_id)




    if request.method == 'POST':
         form = forms.SelectedForm(request.POST)
         if form.is_valid():
             steps_version2 = models.Answer.objects.filter(question_id=question_id).values("text_version")
             steps_versions = list(steps_version2)[0]['text_version']

             percentage_count = models.Answer.objects.filter(question_id=question_id, order='0').values("count")

             check_count = list(percentage_count)[0]['count']
             print("order",check_count)

             percentage_count1 = models.Answer.objects.filter(question_id=question_id, order='1').values("count")
             check_count1 = list(percentage_count1)[0]['count']
             print("order1",check_count1)

             percentage_count2 = models.Answer.objects.filter(question_id=question_id, order='2').values("count")
             check_count2 = list(percentage_count2)[0]['count']
             print("order2",check_count2)

             percentage_count3 = models.Answer.objects.filter(question_id=question_id, order='3').values("count")
             check_count3 = list(percentage_count3)[0]['count']
             print("order3", check_count3)

             add_counts = check_count + check_count1 + check_count2 + check_count3
             print("add count", add_counts)







             select = form.save(commit=False)  # dont put anything in daabase make model quiz instance

             question_idn = models.Question.objects.filter(quiz_id=step.id).values("id")



             print(question_idn.values())
             #the following is uded to extract the id pair value
             ids = list(question_idn)[0]['id']



             #update = models.Answer.objects.get(id=step_pk)  # get correct column from dtabase
             select.question_id = ids

             #get form selected field that you write in

             form_value = select.selected

             select = models.Answer()  # instance of Bactime model
             select.question_id = ids
             models.Answer.objects.filter(question_id=question_id,order=form_value).update(selected="1")

             check = models.Answer.objects.filter(question_id=question_id,order=form_value).values("id")




             check_selected = list(check)[0]['id']
             print(check_selected)

             check1 = models.Answer.objects.filter(question_id=question_id,id=check).values("correct")
             count1 = models.Answer.objects.filter(question_id=question_id, id=check).values("count")
             check_correct = list(check1)[0]['correct']
             print(check_correct)

            # compare = check_selected == check_correct
             #print(compare)
             check1_count = list(count1)[0]['count']

             print(check1_count)

             print("Max count", add_counts)

             def percentage(part, whole):
                 return 100 * float(part) / float(whole)

             # percentage(check1_count, add_counts)
             percentage_send = percentage(check1_count, add_counts)
             print ("percentage ", percentage(check1_count, add_counts))
             previous_version_percentage = models.Answer.objects.filter(question_id=question_id, correct='1').values("previous_version_percentage")
             check_previous_version = list(previous_version_percentage)[0]['previous_version_percentage']
             print ("check_previous_version",check_previous_version)



             if (steps_versions == 2) & (check_previous_version == 0):
                 print("steps_version is 2")
                 models.Answer.objects.filter(question_id=question_id, correct='1').update(
                     previous_version_percentage=percentage_send)
                 print("changed previous version percentage to ",percentage_send)

             pass

             if  check_correct == 1:
                 print("the answer count number is",count1)
                 check1_count = list(count1)[0]['count']

                 print(check1_count)

                 print("Max count", add_counts)



                 def percentage(part, whole):
                     return 100 * float(part) / float(whole)

                 #percentage(check1_count, add_counts)
                 percentage_send = percentage(check1_count, add_counts)
                 print ("percentage " ,percentage(check1_count, add_counts))



                 messages.add_message(request, messages.SUCCESS,
                                      "CORRECT! WELL DONE")
                 # get count value the add 1
                 count = models.Answer.objects.filter(question_id=question_id, order=form_value).values("count")



                 check_count = list(count)[0]['count']
                 print(check_count)

                 count = check_count + 1
                 print(count)

                 models.Answer.objects.filter(question_id=question_id, order=form_value).update(count=count)

                 answer_correct_order = models.Answer.objects.filter(correct="1", question_id=question_id)
                 percentage_save = models.Answer.objects.filter(correct="1", question_id=question_id).update(percentage_correct=percentage_send)  # instance of Answers model
                # select.percentage_correct = "2"
                # print("select.percentage_correct",select.percentage_correct)


             else:

                 messages.add_message(request, messages.SUCCESS,
                                      "WRONG! SORRY")

                 steps_version2 = models.Answer.objects.filter(question_id=question_id).values("text_version")
                 steps_versions = list(steps_version2)[0]['text_version']

                 #get count value the add 1
                 count = models.Answer.objects.filter(question_id=question_id, order=form_value).values("count")

                 check_count = list(count)[0]['count']
                 print(check_count)

                 count = check_count + 1
                 print(count)

                 models.Answer.objects.filter(question_id=question_id, order=form_value).update(count=count)

                 answer_correct_order = models.Answer.objects.filter(correct="1",question_id=question_id)



                 print(answer_correct_order)
                 form = forms.SelectedForm()

            #now compare order value sent from form vs anwser_correct_order


             form = forms.SelectedForm()

            # return HttpResponseRedirect(quiz.get_absolute_url())





    return render(request, 'courses/quiz_detail.html', {
        'step': step,
        'form':form,
        'question_id':question_id,
        'steps':steps,
        'steps_version2':steps_version2,
        'steps_wrong':steps_wrong,

        'answer_correct_order':answer_correct_order,






        })

def query_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Query, course_id=course_pk, pk=step_pk)




  #  quizzes = sorted(chain(step.quiz_set.all(), step.quiz_set.all()),
  #                 key=lambda step: step.order)

    return render(request, 'courses/query_detail.html', {
        'step': step,

        })


def quiz_create(request, course_pk):   #what course this quiz belongs to
    course = get_object_or_404(models.Course, pk=course_pk)

    form = forms.QuizForm()  #create blank form

    if request.method == 'POST':
         form = forms.QuizForm(request.POST)
         if form.is_valid():
             quiz = form.save(commit=False)  #dont put anything in daabase make model quiz instance
             quiz.course = course
             quiz.save()

             messages.add_message(request, messages.SUCCESS,
                                 "Quiz Added!")
             return HttpResponseRedirect(quiz.get_absolute_url())

learning_site/learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'index.html')

def test(request):
    return render(request, 'test.html')

learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}Feedback System{% endblock %}

{% block content %}
<style>

    @import url(https://fonts.googleapis.com/css?family=Roboto:400,100,500,300italic,500italic,700italic,900,300);

body {

}

video {
   max-width:74rem;
   width:100%;
   max-height:30.875rem;
   height:100%;
   margin:0.25rem auto;
   padding:0.051%;
   background-color:#F5F5F5;
}

.flip-container {
  margin: 0 auto;
  -webkit-perspective: 1000;
  -moz-perspective: 1000;
  float: left;
  margin-right: 20px;
}

.flip-container:hover .flipper {
  -webkit-transform: rotateY(180deg);
  -moz-transform: rotateY(180deg);
}

.flipper {
  -webkit-transition: 0.6s;
  -webkit-transform-style: preserve-3d;
  -moz-transition: 0.6s;
  -moz-transform-style: preserve-3d;
  position: relative;
}

.front, .back {
  -webkit-backface-visibility: hidden;
  -moz-backface-visibility: hidden;
  position: absolute;
  top: 0;
  left: 0;
  border: 1px solid #ccc;
}

.front {
  z-index: 1;
  background: #fff;
}

.flip-container, .front, .back {
  width: 300px;
  height: 500px;

}

.back {
  -webkit-transform: rotateY(-180deg);
  -moz-transform: rotateY(-180deg);
  background: #f6f6f6;
}

.flip-padding {
  padding: 20px;
}

.profile-picture {
  width: 300px;
  height: 400px;
}

.button-picture {
  width: 200px;
  height: 30px;
}

.profile-name, .profile-title {
  text-align: center;
}

.profile-name {
  font-size: 24px;
  margin-top: 20px;
  font-weight: 400;
  margin-bottom: 0px;
}

.profile-title {
  font-size: 16px;
  margin-top: 5px;
  font-weight: 300;
  color: #2196F3;
}

.profile-devider {
    width: 100%;
    height: 4px !important;
    background: #07B288;
    position: relative;
  margin: 0 auto;
  margin-top: -4px;
}
.profile-devider:after {
    content:'';
    position: absolute;
    border-style: solid;
    border-width: 15px 15px 0;
    border-color: #07B288 transparent;
    display: block;
    width: 0;
    z-index: 1;
    left: 135px;
}
.logo {
  background: transparent url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMhH24UNs-GDgUH6La-p5vz6HRwBqXVsA6fdWatwwwnCJ09c9daA') center center no-repeat;
  width: 195px;
  background-size: contain;
  text-indent: 100%;
  white-space: nowrap;
  overflow: hidden;
}


</style>
<h1 class="logo">Logo</h1>
    <div class="row">
        <h1>Welcome to My Learning Site</h1>

<!--

    <div class="flip-container">
  <div class="flipper">
    <div class="front">
      <img class="profile-picture"  {% load static %} <img src="{% static 'images/image1.jpg' %}" width="300px" height="300px">
      <div class="profile-devider"></div>
      <h3 class="profile-name">About Me</h3>
      <h4 class="profile-title">Student</h4>
    </div>
    <div class="back">
      <div class="flip-padding">My Name is Stephen Holland and i am currently completing a masters at dcu.</div>
    </div>
  </div>
</div>
        <h3>Project Overview</h3>
            <p>My project is a web application that gathers continues unprompted feedback from uploaded online presentations. The application will analyse and correlate audience feedback information to identify level of audience engagement and understanding of the presented material using statistical methods.
</p>
        <h3>Research question</h3>
        <p>Prove the hypothesis that when students give continues unprompted feedback on a presentation/lecture this Improves the Teaching of the material. Thus Improve the overall learning and understanding of the material.
</p>
          <h3>Your Help</h3>
        <p> For me to prove my hypothesis i need pertictipents to help me. As a perticipient you can pick a course video to watch and give feedback on that video. There are a couple
            of different ways to give feedback.
            <br>1. Use the <img class="button-picture"  {% load static %} <img src="{% static 'images/button.png' %}" width="100px" height="30px"> button when you see apart of the video you dont understand.<br>
                2. Use the <img class="feedback_button"  {% load static %} <img src="{% static 'images/feedback_button.png' %}" width="100px" height="30px"> button to give your feedback on the video.<br>
                3. Afer each video there will be a quiz question on the material shown in the video. I would like perticipents to have ago at answering the question.<br>
                4. During my experiments i will be changing to a newer version of the video lesson.Results  will be statistically shown in the app.


</p>


</div>


--><video width="1200" controls>
  <source src="https://s3-eu-west-1.amazonaws.com/mylearningsitebucket/19CO3.mp4" type="video/mp4">
  <source src="https://s3-eu-west-1.amazonaws.com/mylearningsitebucket/19CO3.mp4" type="video/ogg">
  Your browser does not support HTML5 video.
</video>

<p>

<a href="https://s3-eu-west-1.amazonaws.com/mylearningsitebucket/19CO3.mp4" target="_blank"></a>.
</p>


    </div>




{% endblock %}

learning_site/templates/layout.html
<!doctype html>
{% load static from staticfiles %}
{% load course_extras %}
<html class="no-js" lang="en">
    <head>fffffffffffyyyyy
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
        <link rel="icon" type="image/x-icon" href=" /media/imagesi.png ">

      <!--  <link rel="stylesheet" href="{% static 'css/layout.css' %}">-->
        {% block css %}{% endblock %}
        <script src="{% static 'js/vendor/modernizr.js' %}"></script>
        <meta class="foundation-mq">
        <link rel="stylesheet" href="https://code.jquery.comls/mobile/1.4.5/jquery.mobile-1.4.5.min.css">


        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>


         <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
          <script src="http://api.html5media.info/1.1.5/html5media.min.js"></script>

  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/themes/ui-darkness/jquery-ui.css" rel="stylesheet">

    </head>
    <body>

        <nav class="top-bar" role="navigation">
            <section class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">
                    <li class="menu-text">My Learning Site</li>
                    <li class="has-submenu">
                        <a href="#">Courses</a>

                        <ul class="submenu menu vertical" data-submenu role="menu">
                            {% nav_courses_list %}
                            <li><a href="{% url 'courses:list' %}">See all &rarr;</a></li>

                        </ul>
                    </li>
                </ul>



            </section>
             <section class="top-bar-right">
                <ul class="dropdown menu" data-dropdown-menu role="menubar">

                    <li class="has-submenu">
                        <li><a href="#">Features</a></li>
                        <li><a href="#">Pricing</a></li>
                        <li><a href="#">Sign In</a></li>



                    </li>
                </ul>



            </section>
        </nav>
        {% block content %}{% endblock %}
        <footer class="row columns">
            <hr/>
            <div class="small-6 columns">
                <h7>&copy; My Learning Site</h7>
            </div>
            <div class="small-6 columns">
                <ul class="inline-list no-bullet float-right">
                    <li><a href="{% url 'courses:list' %}">Courses</a></li>
                </ul>
            </div>
        </footer>
       <!-- <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>-->
        <script src="{% static 'js/vendor/what-input.min.js' %}"></script>
        <script src="{% static 'js/foundation.min.js' %}"></script>
        {% block javascript %}{% endblock %}
        <script>$(document).foundation();</script>
    </body>
</html>