learning_site/courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/t(?P<step_pk>\d+)/$', views.text_details,
        name='text'),

    url(r'(?P<course_pk>\d+)/q(?P<step_pk>\d+)/$', views.quiz_detail,
        name='quiz'),
    url(r'(?P<course_pk>\d+)/qy(?P<step_pk>\d+)/$', views.query_detail,
        name='query'),
    url(r'(?P<course_pk>\d+)/create_quiz/$', views.quiz_create,
        name='create_quiz'),

    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/create_query/$', views.query_create,
        name='create_query'),
  #  url(r'(?p<quiz_pk>\d+)/create_question/(?P<question_type>mc|tf)/$', views.create_question,
  #      name='create_question'),

    url(r'(?P<quiz_pk>\d+)/create_question/(?P<question_type>tf|mc)/$', views.create_question,
        name='create_question'),



    url(r'(?P<question_pk>\d+)/create_answer/$', views.answer_form,
        name='create_answer'),


    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),

    url(r'(?P<pk>\d+)v/$', views.feeder_value, name='value'),


]

learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.hello_world, name='home'),
    url(r'^$', views.test, name='test'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator



FEEDBACK_OPTIONS = (
    ('BADLY EXPLAINED', 'Badly Explained'),
    ('TO COMPLICATED', 'To Complicated'),
    ('NOT INTERESTED', 'Not interesting'),
    ('LOVED IT', 'Loved It!!!'),
    ('WELL TAUGHT', 'Well Taught'),
    ('GOOD MATERIAL', 'Good Material'),

)

class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True)
    feeder = models.IntegerField(default=0);
    


    def __unicode__(self):
        return unicode(self.title) or u''


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField( null=True)
   # content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0, null=True)

    course = models.ForeignKey(Course)







    #clickTime = models.IntegerField()
    
    class Meta:
        abstract = [True]
        ordering = ['order',]

    def __unicode__(self):
        return unicode(self.title) or u''

class Text(Step):
    content = models.TextField(blank=True, default='', null=True)
    video = models.FileField( null=True)
    #video = EmbedVideoField()

    time = models.IntegerField(default = 10, null=True)
    version = models.IntegerField(default=1, null=True)
    new = models.TextField(default="Noting new", null=True)
    textversion = models.TextField(default=1, null=True)




    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id,

        })


def __unicode__(self):
    return unicode(self.content) or u''



class Quiz(Step):
    total_questions = models.IntegerField(default=3)
    total_answers = models.IntegerField(default=4)
    correct = models.BooleanField(default=False)
    answer_1 = models.CharField(max_length=255)
    answer_2 = models.CharField(max_length=255)
    answer_3 = models.CharField(max_length=255)
    answer_4 = models.CharField(max_length=255)



    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id
        })



        def __unicode__(self):
            return unicode(self.total_questions) or u''

class Query(models.Model):
    rating = models.IntegerField(default = 0, null=True)
    feedback = models.CharField(max_length=15, choices=FEEDBACK_OPTIONS)
    course = models.ForeignKey(Course)
    step = models.ForeignKey(Text)
    textversion = models.IntegerField(default=0, null=True)


    def get_absolute_url(self):
        return reverse('courses:query', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.step.id
        })


    def __unicode__(self):
        return unicode(self.rating) or u''





class BackTime(models.Model):
    backtimes = models.IntegerField(default = 0, null=True)
    topic = models.CharField(max_length=255, null=True)
    course = models.ForeignKey(Course)
    step = models.ForeignKey(Text)
    textversion = models.IntegerField(default=0,null=True)


    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.step.id,


        })

    def __unicode__(self):
        return unicode(self.backtimes) or u''

class Question(models.Model):
     quiz = models.ForeignKey(Quiz)
     order = models.IntegerField(default=0)
     prompt = models.TextField()

     class Meta:
         ordering = ['order']



     def get_absolute_url(self):
         return self.quiz.get_absolute_url()

     def __str__(self):
         return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0 )
    text = models.CharField(max_length=255)
    correct = models.IntegerField(default=0)
    selected = models.IntegerField(default=0,validators=[
            MaxValueValidator(3),
            MinValueValidator(0)
        ])
    count = models.IntegerField(default=0)
    text_version= models.IntegerField(default=1)
    percentage_correct = models.IntegerField(default=0)
    previous_version_percentage =  models.IntegerField(default=0)


    class Meta:
        ordering = ['order']

    def _str__(self):
        return self.text

learning_site/courses/forms.py
from django import forms

from . import models

#create quiz form


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',

            'total_answers',



        ]

class FormQuiz(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [

            'answer_1',
            'answer_2',


        ]


class QueryForm(forms.ModelForm):
    class Meta:
        model = models.Query
        fields = [

            'rating',
            'feedback',



        ]

class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [

            'order',
            'prompt',





        ]




class BackTime(forms.ModelForm):
    class Meta:
        model = models.BackTime
        fields = [

            'backtimes',

        ]



class AnswersForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct',


        ]

class SelectedForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'selected',

        ]

learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course, Step, Text, Query, Quiz
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
import logging
from django.http import HttpResponse

from . import forms
from . import models

# Include the `fusioncharts.py` file that contains functions to embed the charts.
from .static import fusioncharts





def course_list(request):
    courses = models.Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})


def test(request):
    return HttpResponse("You're looking at question %s.")



def course_detail(request, pk):
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
                   key=lambda step: step.order)
    return render(request, 'courses/course_detail.html', {
            'course': course,
            'steps': steps})



def quiz_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)

    print(step.id)   #Quiz id

    #now get the question id

    question_id = models.Question.objects.filter(quiz_id=step.id).values("id")
    print(question_id) # question_id

    steps = models.Answer.objects.filter(question_id=question_id, text_version='1')
    steps_version2 = models.Answer.objects.filter(question_id=question_id, text_version='2')
    steps_wrong = models.Answer.objects.filter(question_id=question_id,correct='0')



    order = models.Answer.objects.filter(question_id=question_id).values("order")
    print(order)  # orders

    correct = models.Answer.objects.filter(question_id=question_id).values("correct")
    print(correct)  # orders

    #    step_order = get_object_or_404(models.Answer, question_id = question_id)


    #now get the question id
    form = forms.SelectedForm()  #create blank form



 #   print("steps_version2",steps_versions)
    answer_correct_order = models.Answer.objects.filter(correct="1", question_id=question_id)




    if request.method == 'POST':
         form = forms.SelectedForm(request.POST)
         if form.is_valid():
             steps_version2 = models.Answer.objects.filter(question_id=question_id).values("text_version")
             steps_versions = list(steps_version2)[0]['text_version']

             percentage_count = models.Answer.objects.filter(question_id=question_id, order='0').values("count")

             check_count = list(percentage_count)[0]['count']
             print("order",check_count)

             percentage_count1 = models.Answer.objects.filter(question_id=question_id, order='1').values("count")
             check_count1 = list(percentage_count1)[0]['count']
             print("order1",check_count1)

             percentage_count2 = models.Answer.objects.filter(question_id=question_id, order='2').values("count")
             check_count2 = list(percentage_count2)[0]['count']
             print("order2",check_count2)

             percentage_count3 = models.Answer.objects.filter(question_id=question_id, order='3').values("count")
             check_count3 = list(percentage_count3)[0]['count']
             print("order3", check_count3)

             add_counts = check_count + check_count1 + check_count2 + check_count3
             print("add count", add_counts)







             select = form.save(commit=False)  # dont put anything in daabase make model quiz instance

             question_idn = models.Question.objects.filter(quiz_id=step.id).values("id")



             print(question_idn.values())
             #the following is uded to extract the id pair value
             ids = list(question_idn)[0]['id']



             #update = models.Answer.objects.get(id=step_pk)  # get correct column from dtabase
             select.question_id = ids

             #get form selected field that you write in

             form_value = select.selected

             select = models.Answer()  # instance of Bactime model
             select.question_id = ids
             models.Answer.objects.filter(question_id=question_id,order=form_value).update(selected="1")

             check = models.Answer.objects.filter(question_id=question_id,order=form_value).values("id")




             check_selected = list(check)[0]['id']
             print(check_selected)

             check1 = models.Answer.objects.filter(question_id=question_id,id=check).values("correct")
             count1 = models.Answer.objects.filter(question_id=question_id, id=check).values("count")
             check_correct = list(check1)[0]['correct']
             print(check_correct)

            # compare = check_selected == check_correct
             #print(compare)
             check1_count = list(count1)[0]['count']

             print(check1_count)

             print("Max count", add_counts)

             def percentage(part, whole):
                 return 100 * float(part) / float(whole)

             # percentage(check1_count, add_counts)
             percentage_send = percentage(check1_count, add_counts)
             print ("percentage ", percentage(check1_count, add_counts))
             previous_version_percentage = models.Answer.objects.filter(question_id=question_id, correct='1').values("previous_version_percentage")
             check_previous_version = list(previous_version_percentage)[0]['previous_version_percentage']
             print ("check_previous_version",check_previous_version)



             if (steps_versions == 2) & (check_previous_version == 0):
                 print("steps_version is 2")
                 models.Answer.objects.filter(question_id=question_id, correct='1').update(
                     previous_version_percentage=percentage_send)
                 print("changed previous version percentage to ",percentage_send)

             pass

             if  check_correct == 1:
                 print("the answer count number is",count1)
                 check1_count = list(count1)[0]['count']

                 print(check1_count)

                 print("Max count", add_counts)



                 def percentage(part, whole):
                     return 100 * float(part) / float(whole)

                 #percentage(check1_count, add_counts)
                 percentage_send = percentage(check1_count, add_counts)
                 print ("percentage " ,percentage(check1_count, add_counts))



                 messages.add_message(request, messages.SUCCESS,
                                      "CORRECT! WELL DONE")
                 # get count value the add 1
                 count = models.Answer.objects.filter(question_id=question_id, order=form_value).values("count")



                 check_count = list(count)[0]['count']
                 print(check_count)

                 count = check_count + 1
                 print(count)

                 models.Answer.objects.filter(question_id=question_id, order=form_value).update(count=count)

                 answer_correct_order = models.Answer.objects.filter(correct="1", question_id=question_id)
                 percentage_save = models.Answer.objects.filter(correct="1", question_id=question_id).update(percentage_correct=percentage_send)  # instance of Answers model
                # select.percentage_correct = "2"
                # print("select.percentage_correct",select.percentage_correct)


             else:

                 messages.add_message(request, messages.SUCCESS,
                                      "WRONG! SORRY")

                 steps_version2 = models.Answer.objects.filter(question_id=question_id).values("text_version")
                 steps_versions = list(steps_version2)[0]['text_version']

                 #get count value the add 1
                 count = models.Answer.objects.filter(question_id=question_id, order=form_value).values("count")

                 check_count = list(count)[0]['count']
                 print(check_count)

                 count = check_count + 1
                 print(count)

                 models.Answer.objects.filter(question_id=question_id, order=form_value).update(count=count)

                 answer_correct_order = models.Answer.objects.filter(correct="1",question_id=question_id)



                 print(answer_correct_order)
                 form = forms.SelectedForm()

            #now compare order value sent from form vs anwser_correct_order


             form = forms.SelectedForm()

            # return HttpResponseRedirect(quiz.get_absolute_url())





    return render(request, 'courses/quiz_detail.html', {
        'step': step,
        'form':form,
        'question_id':question_id,
        'steps':steps,
        'steps_version2':steps_version2,
        'steps_wrong':steps_wrong,

        'answer_correct_order':answer_correct_order,






        })

def query_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Query, course_id=course_pk, pk=step_pk)




  #  quizzes = sorted(chain(step.quiz_set.all(), step.quiz_set.all()),
  #                 key=lambda step: step.order)

    return render(request, 'courses/query_detail.html', {
        'step': step,

        })


def quiz_create(request, course_pk):   #what course this quiz belongs to
    course = get_object_or_404(models.Course, pk=course_pk)

    form = forms.QuizForm()  #create blank form

    if request.method == 'POST':
         form = forms.QuizForm(request.POST)
         if form.is_valid():
             quiz = form.save(commit=False)  #dont put anything in daabase make model quiz instance
             quiz.course = course
             quiz.save()

             messages.add_message(request, messages.SUCCESS,
                                 "Quiz Added!")
             return HttpResponseRedirect(quiz.get_absolute_url())

learning_site/courses/templates/courses/feeder_value.html
{{ course.feeder }}

learning_site/courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
<li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}

<style>
    .messages{
    color: Red;
    font-size: 30px;

    }



</style>
<div class="row columns">
    <article>
        {{ block.super }}
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li
                    {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}


        <h1>{{ step.title }}</h1>
        <ul class="no-bullet">
            {% for question in step.question_set.all %}
            <li>
                <h2>{{ question.prompt }}</h2>
                {% for answer in question.answer_set.all %}


                <!--{% if answer.correct %}success{% endif %}-->
                <div class="callout {% if answer.correct %}{% endif %}">Option {{ answer.order }}: {{ answer.text }}
                </div>
                {% endfor %}


            </li>
            {% endfor %}
        </ul>
    </article>

    <hr>

    <h3>Select An Option</h3>
    <form method="POST" action="" id="optionForm">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" onclick="show()" class="button" value="Submit">

    </form>

    <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type=" mc" %}" class="button1">New Multiple
    Choice</a>
    <input type="button" class="button" value="Show Results">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>


    <div id="step23">
        {% for step in answer_correct_order %}

        <h4>Percentage version {{ step.text_version }} Correct :{{ step.percentage_correct }}%</h4>


        {% endfor %}
    </div>
    <div id="step24">
        {% for step in answer_correct_order %}

        <h5>Previous Version Percentage Correct :{{ step.previous_version_percentage }}%</h5>


        {% endfor %}
    </div>
    <div id="step_tru25">
        {% for step in answer_correct_order %}

        <div id="par25">{{ step.previous_version_percentage }}</div>


        {% endfor %}


    </div>

    <div id="step_tru26">
        {% for step in answer_correct_order %}

        <div id="par26">{{ step.percentage_correct }}</div>


        {% endfor %}


    </div>


    <canvas id="myChart"></canvas>
    <canvas id="myChart3"></canvas>


    <div id="step_tru1">
        {% for step in steps %}

        <div id="par1">{{ step.count }}</div>


        {% endfor %}


    </div>

    <div id="step_tru2">
        {% for step in steps %}

        <div id="par2">{{ step.text }}</div>


        {% endfor %}


    </div>

    <div id="step_tru3">
        {% for step in steps_wrong %}

        <div id="par3">{{ step.count }}</div>


        {% endfor %}
    </div>

    <div id="step_tru4">
        {% for step in steps_wrong %}

        <div id="par4">{{ step.correct }}</div>


        {% endfor %}


    </div>

    <div id="step_tru5">
        {% for step in steps_version2 %}

        <div id="par5">{{ step.count }}{{ step.percentage_correct }}</div>


        {% endfor %}


    </div>

    <div id="step_tru6">
        {% for step in steps_version2 %}

        <div id="par6">{{ step.text }}{{ step.percentage_correct }}</div>


        {% endfor %}


    </div>


    <script>

      $(document).ready(function(){

                 $("#step_tru1").hide();
                 $("#step_tru2").hide();
                  $("#step_tru3").hide();
                   $("#step_tru4").hide();
                    $("#step_tru5").hide();
                     $("#step_tru6").hide();
                  $("#step_tru25").hide();
                  $("#step_tru26").hide();
                   $("#myChart").hide();
                   $("#myChart3").hide();
                   $("h5").hide();
                   $("h4").hide();



                   var tRow = document.getElementById('step_tru25');
                    var tRow1 = document.getElementById('step_tru26');

                 // var x = tRow.children[0].innerHTML;
                 var all = new Array();
                 var all1 = new Array();

                  for (i=0; i<=23; i++){




                        var x = tRow.children[i].innerHTML;
                         var x1 = tRow1.children[i].innerHTML;

                      all[i]=x;
                      all1[i]=x1;

                       all.sort();
                        all1.sort();



                  funcPie(x,x1);
}









     });


        $(".button_version").click(function(){

                  nextVersion();
            });

              $(".button").click(function(){

                  show();
            });


var ctx = document.getElementById("myChart").getContext('2d');

var ctx3 = document.getElementById("myChart3").getContext('2d');



   /////////   For line time chart   /////////////////////////////////////////////////////////////

                        console.log("before tRow")
                        var tRow = document.getElementById('step_tru2');

                        var tRow1 = document.getElementById('step_tru1');
                        console.log("tRow"+tRow)
                        var i;
                        var all1 = new Array();
                        var i;
                        var i1;

                        var all = new Array();
                        for (i=0; i<=13; i++){

                        var x = tRow.children[i].innerHTML;
                        var y = tRow1.children[i].innerHTML;

                        all[i]=x;

                        all1[i]=y;

                        all.sort();
                        all1.sort();
                        var counts = {};

                        var counts1 = {};

                         all.forEach(function(i) {
                         counts[i] = (counts[i] || 0)+1;


                         });
                          all1.forEach(function(i) {
                         counts1[i] = (counts1[i] || 0)+1;

                         });

                          var count = Object.values(counts);
                          var key = Object.keys(counts);
                          var key1 = Object.keys(counts1);


                        var value = Object.values(counts);
                        console.log("key"+key)
                        console.log("key1"+key1)
                        console.log("count"+count)



                    // callchart.js line chart
                    func(key,key1);



}

function nextVersion(){
              console.log("before tRow")
                        var tRow = document.getElementById('step_tru6');

                        var tRow1 = document.getElementById('step_tru5');
                        console.log("tRow"+tRow)
                        var i;
                        var all1 = new Array();
                        var i;
                        var i1;

                        var all = new Array();
                        for (i=0; i<=13; i++){

                        var x = tRow.children[i].innerHTML;
                        var y = tRow1.children[i].innerHTML;

                        all[i]=x;

                        all1[i]=y;

                        all.sort();
                        all1.sort();
                        var counts = {};

                        var counts1 = {};

                         all.forEach(function(i) {
                         counts[i] = (counts[i] || 0)+1;


                         });
                          all1.forEach(function(i) {
                         counts1[i] = (counts1[i] || 0)+1;

                         });

                          var count = Object.values(counts);
                          var key = Object.keys(counts);
                          var key1 = Object.keys(counts1);


                        var value = Object.values(counts);
                        console.log("key"+key)
                        console.log("key1"+key1)
                        console.log("count"+count)



                    // callchart.js line chart
                    func1(key,key1.reverse());



}



}


   // for Line Chart.js //
              function func(x,y){

              console.log("inside")

                var color =  "rgba(153,255,51,0.6)";
                var chart = new Chart(ctx, {
               type: 'bar',
                data: 'data',
                  options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                max:15,
                                min: 0,
                                stepSize: 2
                            }
                        }]
                    }
                },


                 data:{
                 labels: x,

                datasets: [
                    {
                        label: "Answers Giving",
                          data:y,
                        backgroundColor: [

                            'rgba(255, 159, 64, 1)',
                             'rgba(255, 159, 64, 1)',
                              'rgba(255, 159, 64, 1)',
                               'rgba(255, 159, 64, 1)',
                                'rgba(255, 159, 64, 1)',
                                 'rgba(255, 159, 64, 1)',
                                  'rgba(255, 159, 64, 1)',
                                   'rgba(255, 159, 64, 1)',
                                    'rgba(255, 159, 64, 1)',
                                     'rgba(255, 159, 64, 1)'

                        ],


                    }

                    ,



                   ]




                    },

                    });




            }

             // for Line Chart.js //
              function func1(x,y){

              console.log("inside")

                var color =  "rgba(153,255,51,0.6)";
                var chart = new Chart(ctx, {
               type: 'bar',
                data: 'data',
                  options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                max:5,
                                min: 0,
                                stepSize: 1
                            }
                        }]
                    }
                },


                 data:{
                 labels: x,

                datasets: [
                    {
                        label: "Version 2",
                          data:y,
                        backgroundColor: [

                            'rgba(215, 19, 114, 61)',
                             'rgba(215, 19, 114, 61)',
                               'rgba(215, 19, 114, 61)',
                                'rgba(215, 19, 114, 61)',
                                 'rgba(25, 19, 14, 1)',
                                 'rgba(255, 159, 64, 1)',
                                  'rgba(255, 159, 64, 1)',
                                   'rgba(255, 159, 64, 1)',
                                    'rgba(255, 159, 64, 1)',
                                     'rgba(255, 159, 64, 1)'

                        ],


                    }

                    ,



                   ]




                    },

                    });




            }



function funcPie(value1,value2){
console.log("value1"+value1);
console.log("value2"+value2);

  var color =  "rgba(153,255,51,0.6)";
var myChart3 = new Chart(ctx3, {
    type: 'line',
    data: {
        labels: ["Previous Version","Current version"],
        datasets: [{
            label: '% Difference in version answers',
            data: [value1,value2],
            backgroundColor: [
                'rgba(255, 199, 132, 0.2)',
                 'rgba(255, 199, 332, 3.2)',

            ],
            borderColor: [
                'rgba(255,99,132,1)',
                 'rgba(255, 99, 132, 0.2)',

            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});



}


function show(){


                   $("#myChart").show();
                   $("#myChart3").show();
                   $("h5").show();
                   $("h4").show();





}







    </script>

    <script>

    $("#optionForm3").submit(function(event) {



        //set time back 15 seconds


        //document.write(5 + 6);
        // Stop form from submitting normally
        event.preventDefault();
        var optionForm = $(this);
        // Send the data using post
        var posting = $.post( optionForm.attr('action'), optionForm.serialize() );
        // if success:
          //  vid.currentTime=vid.currentTime-15;
        posting.done(function(data) {
        show();


            // success actions, maybe change submit button to 'friend added' or whatever
        });
        // if failure:
        posting.fail(function(data) {

            // 4xx or 5xx response, alert user about failure
        });
    });

    {% if request.user.is_superuser %}

     $(".button1").show();
    {% else %}
$(".button1").hide();


    {% endif %}


    </script>

</div>
{% endblock %}